# Generated by Django 2.2.12 on 2020-11-13 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Productor', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productor',
            options={'verbose_name': 'productor', 'verbose_name_plural': 'productores'},
        ),
        migrations.AddField(
            model_name='productor',
            name='direccion',
            field=models.CharField(default=1, max_length=60),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productor',
            name='telefono',
            field=models.CharField(default=12, max_length=10),
            preserve_default=False,
        ),
    ]
