# Generated by Django 2.2.12 on 2020-11-13 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Productor', '0002_auto_20201113_1828'),
    ]

    operations = [
        migrations.AddField(
            model_name='productor',
            name='email',
            field=models.EmailField(default=1, max_length=254),
            preserve_default=False,
        ),
    ]
