# Generated by Django 2.2.12 on 2020-11-16 05:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Productor', '0003_productor_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vivero',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.IntegerField()),
                ('nombre', models.CharField(max_length=60)),
                ('productor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Productor.Productor')),
            ],
            options={
                'verbose_name': 'vivero',
                'verbose_name_plural': 'viveros',
            },
        ),
    ]
