# Generated by Django 2.2.12 on 2020-11-29 07:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Vivero', '0002_auto_20201116_0544'),
    ]

    operations = [
        migrations.RenameField(
            model_name='departamento',
            old_name='nombre',
            new_name='nombre_departamento',
        ),
        migrations.RenameField(
            model_name='municipio',
            old_name='nombre',
            new_name='nombre_municipio',
        ),
        migrations.RenameField(
            model_name='vivero',
            old_name='nombre',
            new_name='nombre_vivero',
        ),
    ]
