# Generated by Django 2.2.12 on 2020-11-29 13:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Vivero', '0003_auto_20201129_0757'),
    ]

    operations = [
        migrations.AddField(
            model_name='vivero',
            name='municipio',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Vivero.Municipio'),
            preserve_default=False,
        ),
    ]
