# Generated by Django 3.1.7 on 2021-05-18 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Vivero', '0005_auto_20201129_1500'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departamento',
            name='nombre_departamento',
            field=models.CharField(max_length=100),
        ),
    ]
