# Generated by Django 3.1.7 on 2021-05-18 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Vivero', '0006_auto_20210518_2203'),
    ]

    operations = [
        migrations.AddField(
            model_name='municipio',
            name='estado',
            field=models.CharField(default=3, max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='municipio',
            name='nombre_municipio',
            field=models.CharField(max_length=100),
        ),
    ]
